### ISSUE TITLE
Doesn't import actors (characters) when creating as compendium

### ISSUE THREAD

**Issue by geoidesic** [kakaroto/R20Converter#55]
I'm trying to save different modules in my campaign as compendiums, so that they can be re-used. However I notice that when I enable that compendium and import it, while it lets me import the maps and tokens it does not import the actors.

I'm not sure if this is a bug or if I'm just doing something wrong.

I'm using R20Converter 0.9.3 and the R20Exporter Chrome Extension

**Comment by kakaroto** [comment]
That's not a R20Converter issue, that's how Foundry works, you import a scene, you only get the scene and what's in it (which includes tokens, tiles, drawings, lights, walls, notes).
The tokens will also not be linked anymore to the actors because Foundry doesn't have access to the actors anymore, and even if you had imported them manually before, they would have a different id in the new world.
That's why I usually don't suggest converting as a compendium, because of this specific issue (I think improving that area is planned for 0.7.2 or 0.7.3), and I tell people to convert to worlds, and only use the compendium option if they want to add a specific actor or a journal into their world. It doesn't work well with scenes or roll table. Also, as compendium, you lose the folder organization.

As an alternative, while I haven't tried it myself, I heard good things about the "Adventure Importer/Exporter" module for Foundry, it lets you export world content into a file that you can import into another world, that includes the folders and the actors/scenes/etc.. 

By the way, you can follow on that issue on Foundry's issue tracker here : https://gitlab.com/foundrynet/foundryvtt/-/issues/1925
