### ISSUE TITLE
Unable to change vision on converted PCs

### ISSUE THREAD

**Issue by Teech77** [kakaroto/R20Converter#68]
![C4496DAB-4F91-42A6-B5C9-69CB4CC5C84A](https://user-images.githubusercontent.com/77909006/105620551-5f638000-5dcc-11eb-81ec-a17eff206b35.jpeg)
All the PCs vision is set some crazy number with like 15 remainders. If I try to change it it gives me the error seen in the picture attached.

**Comment by Teech77** [comment]
All modules were disabled and it did not fix it. The PC on the left is a new PC that I made.

**Comment by kakaroto** [comment]
This should be fixed with the new 0.10.0 release from today. I had actually fixed that in a 0.9.12 release but noticed today that I never made that release public 🤦‍♂️ 
For an existing converted world, you can still fix it with this trick : 
1 - open the token config window
2 - set the values to an integer value
3 - Press F12 to open the dev console
4 - type this command and press enter : `$("form").attr("novalidate", true)`
5 - save the token config
6 - reload the page just in case it messed up anything else it shouldn't have
