### ISSUE TITLE
Nameless tokens imported as tiles

### ISSUE THREAD

**Issue by nulmas** [kakaroto/R20Converter#71]
I had a few villagers in a scene that I couldn't select or move. Once I switched to the tile layer, they became selectable.

I went back to my Roll20 Campaign and noticed that every nameless token was imported as a tile. I'm not sure if it only has to have a name or if the nameplate has to be visible.

**Comment by kakaroto** [comment]
The issue is that in Roll20, even the map is a "token". The only way to differentiate between tiles and tokens is on whether in roll20, it is associated with a character sheet.
R20Converter will also convert an image that "has vision" or has a nameplate, or has bars, into tokens, even if their "Represents" character is set to None.
