### ISSUE TITLE
Any way to bypass the JSON Check?

### ISSUE THREAD

**Issue by dptycaveman** [kakaroto/R20Converter#88]
I purchased a roll20 world from someone's Patreon with the hopes of being able to convert it to Foundry. Due to not building the world myself in Roll20 I don't have a JSON file related to it. I'd really rather not have to purchase a Roll20 sub just to re-export to convert modules and the like from places like DMs Guild. Is there any way to just bypass that check or create a dummy JSON?

**Comment by kakaroto** [comment]
I don't quite understand the question. If you have a campaign in Roll20, you can export it. It doesn't matter if you created it yourself or bought it on the roll20 marketplace. You also don't need a roll20 sub in order to export your campaign (including lighting information), that works perfectly fine using the free tier. You just need to be set as DM for the campaign before you do the export.
I hope that helps. Feel free to re-open the issue if you have need of further help.
